import jsPDF from "jspdf";
import type { ModelResponse } from "./api";

export function generateHomeworkPDF(
  responses: ModelResponse[],
  taskType: string
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPosition = 20;

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("DutchMaster AI - Homework Analysis", margin, yPosition);
  yPosition += 10;

  // Metadata
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  doc.text(`Generated: ${date}`, margin, yPosition);
  yPosition += 5;
  doc.text(`Task Type: ${formatTaskType(taskType)}`, margin, yPosition);
  yPosition += 15;

  doc.setTextColor(0);

  // Each model response
  responses.forEach((response, index) => {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    // Model header
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    const modelColor = getModelColor(response.model_name);
    doc.setTextColor(modelColor.r, modelColor.g, modelColor.b);
    doc.text(`${index + 1}. ${response.model_name}`, margin, yPosition);
    yPosition += 8;

    // Response content
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);

    // Clean markdown and split into lines
    const cleanContent = stripMarkdown(response.content);
    const lines = doc.splitTextToSize(cleanContent, contentWidth);

    lines.forEach((line: string) => {
      if (yPosition > 280) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(line, margin, yPosition);
      yPosition += 5;
    });

    // Idiom analysis if present
    if (response.idiom_analysis?.idioms?.length) {
      yPosition += 5;
      if (yPosition > 260) {
        doc.addPage();
        yPosition = 20;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text("Idioms Found:", margin, yPosition);
      yPosition += 6;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);

      response.idiom_analysis.idioms.forEach((idiom: { expression?: string; meaning?: string; origin?: string }) => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }

        if (idiom.expression) {
          doc.setFont("helvetica", "bold");
          doc.text(`• ${idiom.expression}`, margin + 5, yPosition);
          yPosition += 5;
        }

        doc.setFont("helvetica", "normal");
        if (idiom.meaning) {
          const meaningLines = doc.splitTextToSize(`Meaning: ${idiom.meaning}`, contentWidth - 10);
          meaningLines.forEach((line: string) => {
            if (yPosition > 280) {
              doc.addPage();
              yPosition = 20;
            }
            doc.text(line, margin + 10, yPosition);
            yPosition += 4;
          });
        }

        if (idiom.origin) {
          const originLines = doc.splitTextToSize(`Origin: ${idiom.origin}`, contentWidth - 10);
          originLines.forEach((line: string) => {
            if (yPosition > 280) {
              doc.addPage();
              yPosition = 20;
            }
            doc.text(line, margin + 10, yPosition);
            yPosition += 4;
          });
        }
        yPosition += 3;
      });
    }

    yPosition += 10;
  });

  // Footer on last page
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount} - Generated by DutchMaster AI`,
      pageWidth / 2,
      290,
      { align: "center" }
    );
  }

  // Download
  const filename = `dutchmaster-analysis-${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
}

function formatTaskType(taskType: string): string {
  const labels: Record<string, string> = {
    tekst: "Tekst (Chapter Text)",
    oefening_1_grammatica: "Oefening 1 - Grammatica",
    oefening_2_lezen: "Oefening 2 - Lezen",
    oefening_3_woordvolgorde: "Oefening 3 - Woordvolgorde",
    oefening_4_uitdrukkingen: "Oefening 4 - Uitdrukkingen",
    oefening_5_voorzetsels: "Oefening 5 - Voorzetsels",
    oefening_6_spelling: "Oefening 6 - Spelling",
    oefening_7_woordenschat: "Oefening 7 - Woordenschat",
    oefening_8_opstel: "Oefening 8 - Opstel",
    oefening_9_luisteren_spreken: "Oefening 9 - Luisteren/Spreken",
  };
  return labels[taskType] || taskType;
}

function getModelColor(modelName: string): { r: number; g: number; b: number } {
  const name = modelName.toLowerCase();
  if (name.includes("gpt") || name.includes("o1") || name.includes("o3") || name.includes("openai")) {
    return { r: 34, g: 139, b: 34 }; // Green
  }
  if (name.includes("claude")) {
    return { r: 128, g: 0, b: 128 }; // Purple
  }
  if (name.includes("gemini")) {
    return { r: 30, g: 100, b: 200 }; // Blue
  }
  return { r: 0, g: 0, b: 0 }; // Black
}

function stripMarkdown(text: string): string {
  return text
    .replace(/#{1,6}\s?/g, "") // Headers
    .replace(/\*\*([^*]+)\*\*/g, "$1") // Bold
    .replace(/\*([^*]+)\*/g, "$1") // Italic
    .replace(/__([^_]+)__/g, "$1") // Bold alt
    .replace(/_([^_]+)_/g, "$1") // Italic alt
    .replace(/`([^`]+)`/g, "$1") // Inline code
    .replace(/```[\s\S]*?```/g, "") // Code blocks
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1") // Links
    .replace(/^\s*[-*+]\s+/gm, "• ") // Unordered lists
    .replace(/^\s*\d+\.\s+/gm, "") // Ordered lists
    .replace(/>\s?/g, "") // Blockquotes
    .trim();
}
